In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [6]:
url= 'https://raw.githubusercontent.com/edyoda/data-science-complete-tutorial/master/Data/house_rental_data.csv.txt'

In [20]:
data =pd.read_csv(url,sep=",")
data

Unnamed: 0      Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom  \
0             1  1177.698      2           7        2            2         2   
1             2  2134.800      5           7        4            2         2   
2             3  1138.560      5           7        2            2         1   
3             4  1458.780      2           7        3            2         2   
4             5   967.776     11          14        3            2         2   
..          ...       ...    ...         ...      ...          ...       ...   
640         644  1359.156      7          15        3            2         2   
641         645   377.148      4          10        1            1         1   
642         646   740.064     13          14        1            1         1   
643         647  1707.840      3          14        3            2         2   
644         648  1376.946      6           7        3            2         1   

     Price  
0    62000  
1    78000  
2    58000  
3    45000  
4    45000  
..     ...  
640  45000  
641  24800  
642  45000  
643  65000  
644  36000  

[645 rows x 8 columns]

### 1. Data cleaning & getting rid of irrelevant information before clustering

In [21]:
data = data.drop('Unnamed: 0',axis=1)
data.head()

Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom  Price
0  1177.698      2           7        2            2         2  62000
1  2134.800      5           7        4            2         2  78000
2  1138.560      5           7        2            2         1  58000
3  1458.780      2           7        3            2         2  45000
4   967.776     11          14        3            2         2  45000

In [22]:
data.shape

(645, 7)

In [23]:
data.isnull().sum()

Sqft           0
Floor          0
TotalFloor     0
Bedroom        0
Living.Room    0
Bathroom       0
Price          0
dtype: int64

In [24]:
data.drop_duplicates()

Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom   Price
0    1177.698      2           7        2            2         2   62000
1    2134.800      5           7        4            2         2   78000
2    1138.560      5           7        2            2         1   58000
3    1458.780      2           7        3            2         2   45000
4     967.776     11          14        3            2         2   45000
..        ...    ...         ...      ...          ...       ...     ...
639  2846.400      5          12        4            2         2  138888
640  1359.156      7          15        3            2         2   45000
641   377.148      4          10        1            1         1   24800
642   740.064     13          14        1            1         1   45000
644  1376.946      6           7        3            2         1   36000

[579 rows x 7 columns]

In [25]:
data.dtypes

Sqft           float64
Floor            int64
TotalFloor       int64
Bedroom          int64
Living.Room      int64
Bathroom         int64
Price            int64
dtype: object

In [26]:
data.describe()

Sqft       Floor  TotalFloor     Bedroom  Living.Room  \
count   645.000000  645.000000  645.000000  645.000000   645.000000   
mean   1527.656260    5.939535   10.855814    2.837209     1.813953   
std     767.386531    3.884721    4.996208    1.010740     0.462364   
min     359.358000    1.000000    1.000000    1.000000     0.000000   
25%     925.080000    3.000000    7.000000    2.000000     2.000000   
50%    1423.200000    5.000000   12.000000    3.000000     2.000000   
75%    1892.856000    8.000000   14.000000    4.000000     2.000000   
max    5856.468000   22.000000   38.000000    7.000000     4.000000   

         Bathroom          Price  
count  645.000000     645.000000  
mean     1.810853   61986.823256  
std      0.683574   35635.091007  
min      0.000000    6100.000000  
25%      1.000000   39000.000000  
50%      2.000000   50000.000000  
75%      2.000000   75000.000000  
max      5.000000  250000.000000

### 2. Finding the optimal value of k

- for creating clusterning algorithm we consider few column

In [27]:
x= data[['Sqft','Bedroom']]
x.head()

Sqft  Bedroom
0  1177.698        2
1  2134.800        4
2  1138.560        2
3  1458.780        3
4   967.776        3

- Creating the numpy array of the dataframe from step 4

In [28]:
x= x.iloc[:,:].values
x

array([[1.177698e+03, 2.000000e+00],
       [2.134800e+03, 4.000000e+00],
       [1.138560e+03, 2.000000e+00],
       ...,
       [7.400640e+02, 1.000000e+00],
       [1.707840e+03, 3.000000e+00],
       [1.376946e+03, 3.000000e+00]])

- Apply K-Means Clustering algorithm on data

In [29]:
from sklearn.cluster import KMeans
kmeans = KMeans()
kmeans

KMeans()

In [30]:
kmeans.fit(x)

KMeans()

- Checking the center values of the clusters

In [31]:
kmeans.cluster_centers_

array([[6.51843098e+02, 1.59016393e+00],
       [2.17623348e+03, 3.55913978e+00],
       [1.41416455e+03, 3.00000000e+00],
       [3.74953900e+03, 3.33333333e+00],
       [2.97888868e+03, 3.71052632e+00],
       [1.03229048e+03, 2.52066116e+00],
       [1.78767047e+03, 3.35922330e+00],
       [5.31031500e+03, 4.25000000e+00]])

- Apply Kmeans clustering with different k value

In [34]:
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters = 4)
kmeans

KMeans(n_clusters=4)

In [36]:
kmeans.fit(x)

KMeans(n_clusters=4)

In [39]:
kmeans.cluster_centers_

array([[7.42175341e+02, 1.80219780e+00],
       [2.01111168e+03, 3.50000000e+00],
       [3.37832100e+03, 3.66000000e+00],
       [1.35365442e+03, 2.94273128e+00]])

### Storing cluster to which the house belongs along with the data